export default {
	index: "Index",
	services: "Services",
	technologies: "Technologies",
	products: "Products",
	portfolio: "Portfolio",
	blog: "Blog",
	article: "Article",
	about: "About",
	team: "Team",
	contacts: "Contacts",
	join: "Join",
	author: "Author",
	notFound: "NotFound",
}
